version: "3"

services:
  jenkins:
    build:
      dockerfile: Dockerfile.jenkins
    restart: unless-stopped
    environment:
      DOCKER_CERT_PATH: /certs/client
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: 1
    userns_mode: "host"
    privileged: true
    user: root
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080

  docker:
    image: docker:dind
    privileged: true
    restart: unless-stopped
    userns_mode: "host"
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
    expose:
      - 2376


volumes:
  jenkins-docker-certs:
  jenkins-data: